### ISSUE TITLE
'ModelInfo' object has no attribute 'securityStatus'

### ISSUE THREAD

**Issue by weigary** [huggingface/Google-Cloud-Containers#116]
Hi HF team,

We used to use the `hf_api.model_info().securityStatus` to check if the model repo contains any unsafe files, see the sample call below

```python
from huggingface_hub import HfApi

hf_api = HfApi(
    endpoint="https://huggingface.co",
)

model_info = hf_api.model_info(repo_id="google/gemma-2-27b", securityStatus=True)
print(model_info.securityStatus)
```

It stopped working as we found it today.

Error message:
```
Cell In[4], line 8
      3 hf_api = HfApi(
      4     endpoint="https://huggingface.co",
      5 )
      7 model_info = hf_api.model_info(repo_id="google/gemma-2-27b", securityStatus=True)
----> 8 print(model_info.securityStatus)

AttributeError: 'ModelInfo' object has no attribute 'securityStatus'
```

Still investigating, but it seems it is not related to the version of the huggingface_hub libarary version. For example, the latest lib version in Google3 is 0.25.1, while the previous version is 0.24.6, which is the version we found it was working. However, even if we downgrade the lib version to 0.24.6, the same API call still does not work.

**Comment by weigary** [comment]
It seems the API response has been changed to:

https://huggingface.co/api/models/google/gemma-2-27b?securityStatus=1

```
  "securityRepoStatus": {
    "scansDone": false,
    "filesWithIssues": []
  },
  
```

**Comment by weigary** [comment]
Is it a long-term change?

**Comment by suzukimain** [comment]
Hello. @weigary
Do you have any new information on this issue?

**Comment by weigary** [comment]
Thank you Celina. I am using the `model_info.securityRepoStatus` which seems to work for now. I will update my code to start using the `model_info.security_repo_status`!

**Comment by weigary** [comment]
Mark it as closed.
