### ISSUE TITLE
Download model files from GCS (Instead of HF Hub)

### ISSUE THREAD

**Issue by rm-jeremyduplessis** [huggingface/Google-Cloud-Containers#73]
When deploying an HF model to Vertex AI, I would like to download a fine-tuned model from GCS, instead of from HF Hub, like so:

```
model = aiplatform.Model.upload(
    display_name="my-model",
    serving_container_image_uri=os.getenv("CONTAINER_URI"),
    serving_container_environment_variables={
        "AIP_STORAGE_URI": "gs://path/to/model/files",
    },
    serving_container_ports=[8080],
)
model.wait()
```

I would expect this to be supported since the entrypoint script logic should handle this: https://github.com/huggingface/Google-Cloud-Containers/blob/main/containers/tei/cpu/1.4.0/entrypoint.sh 

Will this be supported when V1.4 is released? When will this be?

**Comment by philschmid** [comment]
Thank you for opening the issue @rm-jeremyduplessis. We are working with the google team to get a ETA. Will report back here.

**Comment by alvarobartt** [comment]
Hi here @rm-jeremyduplessis, TEI 1.4 just got recently released, I'll go and update now the references within the repository; in the meantime, feel free to use the following container URI:

us-docker.pkg.dev/deeplearning-platform-release/gcr.io/huggingface-text-embeddings-inference-cu122.1-4.ubuntu2204

You should be able to provide the `artifact_uri` with the Google Cloud Storage (GCS) Bucket with the model as show below:

```python
model = aiplatform.Model.upload(
    display_name="my-model",
    artifact_uri="gs://path/to/model/files",
    serving_container_image_uri=os.getenv("CONTAINER_URI"),
    serving_container_ports=[8080],
)
model.wait()
```

> [!NOTE]
> I updated your code snippet to use the `artifact_uri` instead which is essentially the same as using the `AIP_STORAGE_URI`, but with the minor difference that this way the `AIP_STORAGE_URI` environment variable is internally set by the `python-aiplatform` SDK; which is the recommended way, even though if you can easily bypass that setting the environment variable yourself as you did above. So feel free to go with whatever works better for your use case, while keeping in mind using the `artifact_uri` is the recommended approach!

**Comment by rm-jeremyduplessis** [comment]
Hi @alvarobartt,

Thanks so much for this!

I've been able to deploy `infloat/e5-small` (no fine-tuning) to a Vertex Endpoint to test like so:

```
model.deploy(
    endpoint=endpoint,
    machine_type="n1-standard-16",
    accelerator_type="NVIDIA_TESLA_T4",
    accelerator_count=1,
    min_replica_count=1,
    max_replica_count=1,
    sync=True
)
model.wait()
```

And while it did work, I've found what I think is a bug: I'm not sure exactly what's causing it, but if you switch between giving a single input like:

```
output = endpoint.predict(instances=[{"inputs": "What is Deep Learning?"}])
```

to a batch, like:

```
output = endpoint.predict(instances=[{"inputs": ["What is Deep Learning?", "What is Deep **Learning?"]}])
```

a few times, then eventually the model endpoint will happily return a vector full of `null` values without failing or restarting.

I checked the endpoint metrics like CPU usage etc. and I can confirm it's not an OOM error or anything like that -- have you experienced this before?

**Comment by alvarobartt** [comment]
Thanks for reporting @rm-jeremyduplessis and for the detailed issue, we'll investigate this and come back to you, did you experienced the same within ghcr.io/huggingface/text-embeddings-inference container i.e. the one published within the https://github.com/huggingface/text-embeddings-inference repository? Thanks again!

**Comment by rm-jeremyduplessis** [comment]
@alvarobartt I just tested with `ghcr.io/huggingface/text-embeddings-inference:turing-1.4` with  `intfloat/e5-large-v2` on an Nvidia T4 and it appears to work fine (no `null` vectors) - I hope that helps!

**Comment by alvarobartt** [comment]
Hmm that's odd @rm-jeremyduplessis I just tried with the same model on the Hugging Face DLC for TEI on Vertex AI and these are the results of 32 consecutive requests:

![image](https://github.com/user-attachments/assets/d4f60054-a0be-4367-9c49-2939566f7db5)

What I've seen is that in your code you're using `requests` instead of sending those over via the Vertex AI SDK for Python, is there any reason for that? Here you can find the Jupyter Notebook attached to reproduce on your end, I guess the settings are the same, the only difference may be on the inference code.

![image](https://github.com/user-attachments/assets/4083d109-a496-4b37-968e-611839186bcc)

**Comment by alvarobartt** [comment]
P.S. Also @rm-jeremyduplessis note that by default Vertex AI will be sending the prediction requests to the `/predict` route even though underneath is calling `/embed` so you should ideally use `/predict` instead when working on Vertex AI.

**Comment by alvarobartt** [comment]
Hi here @rm-jeremyduplessis! FYI the Text Embeddings Inference (TEI) 1.4 DLC for CPU was also released recently, meaning that now you can use download the artifacts from a Google Cloud Storage (GCS) bucket for CPU deployments too.

These are the DLC URIs for both CPU and GPU, in case it's helpful:

- CPU at us-docker.pkg.dev/deeplearning-platform-release/gcr.io/huggingface-text-embeddings-inference-cpu.1-4
- GPU at us-docker.pkg.dev/deeplearning-platform-release/gcr.io/huggingface-text-embeddings-inference-cu122.1-4.ubuntu2204

That being said, I'll close the issue already as it's considered solved, but please don't hesitate on letting us know if you still find any other issue! Thanks for reporting 🤗
