### ISSUE TITLE
Add Cloud Run documentation+support

### ISSUE THREAD

**Issue by jasonsmithio** [huggingface/Google-Cloud-Containers#75]
With the recent launch of [Cloud Run with GPUs](https://cloud.google.com/blog/products/application-development/run-your-ai-inference-applications-on-cloud-run-with-nvidia-gpus), we should update the documentation to include some examples. Happy to test and document over the next few weeks.

**Comment by alvarobartt** [comment]
Hi here @jasonsmithio thanks for bringing this up! I'll try to ship some examples during the coming weeks!
