### ISSUE TITLE
Add `trending_score` to the output of the hf_api.model_info() call

### ISSUE THREAD

**Issue by weigary** [huggingface/Google-Cloud-Containers#99]
Hi,

It would be better to add the `trending_score` as of the property to the output of the API call `hf_api.model_info()`. 

I see there is a PR (https://github.com/huggingface/huggingface_hub/commit/fe39a9694dd8b555a02b4786fc6f686558cfec66) so probably it is already there, but can we have a new release to include this change?

Thanks!

**Comment by alvarobartt** [comment]
Hi here @weigary, yes, indeed that was shipped within the `huggingface_hub` 0.25.0 relase, so installing as `pip install --upgrade huggingface_hub` should do the work!

See the release notes at https://github.com/huggingface/huggingface_hub/releases/tag/v0.25.0
